# Generated by Django 4.2.7 on 2026-03-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumeanalysis',
            old_name='improved_bullets_json',
            new_name='advanced_skill_gaps_json',
        ),
        migrations.RenameField(
            model_name='resumeanalysis',
            old_name='missing_skills_json',
            new_name='career_roadmap_json',
        ),
        migrations.RenameField(
            model_name='resumeanalysis',
            old_name='suggestions_json',
            new_name='critical_skill_gaps_json',
        ),
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='jd_data_json',
        ),
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='resume_data_json',
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='detected_role',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='experience_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='personalized_advice',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='resume_weaknesses_json',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
