# Generated by Django 4.2.7 on 2026-07-31 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0003_emailverificationtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
