# Generated by Django 4.2.7 on 2026-08-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0004_delete_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='skill_match_breakdown_json',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
